import { TEMPLATE_NAMES, VALID_AGENT_IDS } from "@skilltap/core";

export function generateFishCompletions(): string {
  const agentList = VALID_AGENT_IDS.join(" ");
  const templateList = TEMPLATE_NAMES.join(" ");
  return `# skilltap fish completions
# Generated by: skilltap completions fish

# Disable default file completions for skilltap
complete -c skilltap -f

# Top-level commands
complete -c skilltap -n '__fish_use_subcommand' -a status -d 'Show installed components and configuration'
complete -c skilltap -n '__fish_use_subcommand' -a install -d 'Install a skill, plugin, or MCP server'
complete -c skilltap -n '__fish_use_subcommand' -a remove -d 'Remove an installed skill, plugin, or MCP server'
complete -c skilltap -n '__fish_use_subcommand' -a update -d 'Update installed skills, plugins, and MCP servers'
complete -c skilltap -n '__fish_use_subcommand' -a find -d 'Search for skills'
complete -c skilltap -n '__fish_use_subcommand' -a create -d 'Create a new skill'
complete -c skilltap -n '__fish_use_subcommand' -a doctor -d 'Check environment and state'
complete -c skilltap -n '__fish_use_subcommand' -a migrate -d 'Migrate legacy setup to current state'
complete -c skilltap -n '__fish_use_subcommand' -a sync -d 'Show drift between manifest, lockfile, and state'
complete -c skilltap -n '__fish_use_subcommand' -a try -d 'Preview a skill, plugin, or MCP without installing'
complete -c skilltap -n '__fish_use_subcommand' -a toggle -d 'Toggle a skill, plugin, or component active state'
complete -c skilltap -n '__fish_use_subcommand' -a adopt -d 'Bring an external skill or agent-managed plugin into skilltap'
complete -c skilltap -n '__fish_use_subcommand' -a move -d 'Move a skill between scopes'
complete -c skilltap -n '__fish_use_subcommand' -a info -d 'Show details for a skill, plugin, or MCP server'
complete -c skilltap -n '__fish_use_subcommand' -a config -d 'Interactive setup wizard'
complete -c skilltap -n '__fish_use_subcommand' -a tap -d 'Manage taps'
complete -c skilltap -n '__fish_use_subcommand' -a completions -d 'Generate shell completions'
complete -c skilltap -n '__fish_use_subcommand' -a self-update -d 'Update the skilltap binary'

# install — typed subcommands
complete -c skilltap -n '__fish_seen_subcommand_from install; and not __fish_seen_subcommand_from skill plugin mcp' -a 'skill' -d 'Install a skill'
complete -c skilltap -n '__fish_seen_subcommand_from install; and not __fish_seen_subcommand_from skill plugin mcp' -a 'plugin' -d 'Install a plugin'
complete -c skilltap -n '__fish_seen_subcommand_from install; and not __fish_seen_subcommand_from skill plugin mcp' -a 'mcp' -d 'Install an MCP server'
# install skill flags
complete -c skilltap -n '__fish_seen_subcommand_from install; and __fish_seen_subcommand_from skill' -l scope -xa 'project global' -d 'Install scope'
complete -c skilltap -n '__fish_seen_subcommand_from install; and __fish_seen_subcommand_from skill' -l also -xa '${agentList}' -d 'Symlink to agent dir'
complete -c skilltap -n '__fish_seen_subcommand_from install; and __fish_seen_subcommand_from skill' -l ref -x -d 'Branch or tag'
complete -c skilltap -n '__fish_seen_subcommand_from install; and __fish_seen_subcommand_from skill' -l yes -d 'Auto-accept'
complete -c skilltap -n '__fish_seen_subcommand_from install; and __fish_seen_subcommand_from skill' -l strict -d 'Abort on warnings'
complete -c skilltap -n '__fish_seen_subcommand_from install; and __fish_seen_subcommand_from skill' -l semantic -d 'Force semantic scan'
complete -c skilltap -n '__fish_seen_subcommand_from install; and __fish_seen_subcommand_from skill' -l skip-scan -d 'Skip security scan'
complete -c skilltap -n '__fish_seen_subcommand_from install; and __fish_seen_subcommand_from skill' -l quiet -d 'Suppress install step details'
complete -c skilltap -n '__fish_seen_subcommand_from install; and __fish_seen_subcommand_from skill' -l json -d 'Output as JSON'
complete -c skilltap -n '__fish_seen_subcommand_from install; and __fish_seen_subcommand_from skill' -xa '(skilltap --get-completions tap-skills 2>/dev/null)'
# install plugin flags
complete -c skilltap -n '__fish_seen_subcommand_from install; and __fish_seen_subcommand_from plugin' -l scope -xa 'project global' -d 'Install scope'
complete -c skilltap -n '__fish_seen_subcommand_from install; and __fish_seen_subcommand_from plugin' -l also -xa '${agentList}' -d 'Symlink to agent dir'
complete -c skilltap -n '__fish_seen_subcommand_from install; and __fish_seen_subcommand_from plugin' -l ref -x -d 'Branch or tag'
complete -c skilltap -n '__fish_seen_subcommand_from install; and __fish_seen_subcommand_from plugin' -l yes -d 'Auto-accept'
complete -c skilltap -n '__fish_seen_subcommand_from install; and __fish_seen_subcommand_from plugin' -l strict -d 'Abort on warnings'
complete -c skilltap -n '__fish_seen_subcommand_from install; and __fish_seen_subcommand_from plugin' -l semantic -d 'Force semantic scan'
complete -c skilltap -n '__fish_seen_subcommand_from install; and __fish_seen_subcommand_from plugin' -l skip-scan -d 'Skip security scan'
complete -c skilltap -n '__fish_seen_subcommand_from install; and __fish_seen_subcommand_from plugin' -l json -d 'Output as JSON'
# install mcp flags
complete -c skilltap -n '__fish_seen_subcommand_from install; and __fish_seen_subcommand_from mcp' -l scope -xa 'project global' -d 'Install scope'
complete -c skilltap -n '__fish_seen_subcommand_from install; and __fish_seen_subcommand_from mcp' -l yes -d 'Auto-accept'
complete -c skilltap -n '__fish_seen_subcommand_from install; and __fish_seen_subcommand_from mcp' -l json -d 'Output as JSON'

# remove — typed subcommands
complete -c skilltap -n '__fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from skill plugin mcp' -a 'skill' -d 'Remove an installed skill'
complete -c skilltap -n '__fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from skill plugin mcp' -a 'plugin' -d 'Remove an installed plugin'
complete -c skilltap -n '__fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from skill plugin mcp' -a 'mcp' -d 'Remove an installed MCP server'
complete -c skilltap -n '__fish_seen_subcommand_from remove; and __fish_seen_subcommand_from skill' -l scope -xa 'project global' -d 'Remove from scope'
complete -c skilltap -n '__fish_seen_subcommand_from remove; and __fish_seen_subcommand_from skill' -l yes -d 'Skip confirmation'
complete -c skilltap -n '__fish_seen_subcommand_from remove; and __fish_seen_subcommand_from skill' -l json -d 'Output as JSON'
complete -c skilltap -n '__fish_seen_subcommand_from remove; and __fish_seen_subcommand_from skill' -xa '(skilltap --get-completions installed-skills 2>/dev/null)'
complete -c skilltap -n '__fish_seen_subcommand_from remove; and __fish_seen_subcommand_from plugin' -l scope -xa 'project global' -d 'Remove from scope'
complete -c skilltap -n '__fish_seen_subcommand_from remove; and __fish_seen_subcommand_from plugin' -l yes -d 'Skip confirmation'
complete -c skilltap -n '__fish_seen_subcommand_from remove; and __fish_seen_subcommand_from plugin' -l json -d 'Output as JSON'
complete -c skilltap -n '__fish_seen_subcommand_from remove; and __fish_seen_subcommand_from plugin' -xa '(skilltap --get-completions installed-plugins 2>/dev/null)'
complete -c skilltap -n '__fish_seen_subcommand_from remove; and __fish_seen_subcommand_from mcp' -l scope -xa 'project global' -d 'Remove from scope'
complete -c skilltap -n '__fish_seen_subcommand_from remove; and __fish_seen_subcommand_from mcp' -l yes -d 'Skip confirmation'
complete -c skilltap -n '__fish_seen_subcommand_from remove; and __fish_seen_subcommand_from mcp' -l json -d 'Output as JSON'

# update flags
complete -c skilltap -n '__fish_seen_subcommand_from update' -l yes -d 'Auto-accept'
complete -c skilltap -n '__fish_seen_subcommand_from update' -l strict -d 'Abort on warnings'
complete -c skilltap -n '__fish_seen_subcommand_from update' -l semantic -d 'Force semantic scan'
complete -c skilltap -n '__fish_seen_subcommand_from update' -l json -d 'Output result as JSON'
complete -c skilltap -n '__fish_seen_subcommand_from update' -l skip-scan -d 'Skip security scan'
complete -c skilltap -n '__fish_seen_subcommand_from update' -l quiet -d 'Suppress output details'
complete -c skilltap -n '__fish_seen_subcommand_from update' -s c -l check -d 'Check for updates without applying'
complete -c skilltap -n '__fish_seen_subcommand_from update' -s f -l force -d 'Force update even if already up to date'
complete -c skilltap -n '__fish_seen_subcommand_from update' -xa '(skilltap --get-completions installed-skills 2>/dev/null)'

# find flags
complete -c skilltap -n '__fish_seen_subcommand_from find' -l json -d 'JSON output'
complete -c skilltap -n '__fish_seen_subcommand_from find' -s i -d 'Interactive mode'
complete -c skilltap -n '__fish_seen_subcommand_from find' -s l -l local -d 'Search local taps only'

# info flags and dynamic installed skill names
complete -c skilltap -n '__fish_seen_subcommand_from info' -l json -d 'JSON output'
complete -c skilltap -n '__fish_seen_subcommand_from info' -l scope -xa 'project global' -d 'Filter to scope'
complete -c skilltap -n '__fish_seen_subcommand_from info' -xa '(skilltap --get-completions installed-skills 2>/dev/null)'

# create flags
complete -c skilltap -n '__fish_seen_subcommand_from create' -l template -xa '${templateList}' -d 'Template type'
complete -c skilltap -n '__fish_seen_subcommand_from create' -l dir -d 'Target directory'

# config flags
complete -c skilltap -n '__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from security telemetry get set edit' -l reset -d 'Overwrite existing config'

# config subcommands
complete -c skilltap -n '__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from security telemetry get set edit' -a 'security' -d 'Configure security settings'
complete -c skilltap -n '__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from security telemetry get set edit' -a 'telemetry' -d 'Manage telemetry settings'
complete -c skilltap -n '__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from security telemetry get set edit' -a 'get' -d 'Get a config value'
complete -c skilltap -n '__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from security telemetry get set edit' -a 'set' -d 'Set a config value'
complete -c skilltap -n '__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from security telemetry get set edit' -a 'edit' -d 'Open config in editor'
complete -c skilltap -n '__fish_seen_subcommand_from config; and __fish_seen_subcommand_from get' -l json -d 'Output as JSON'
complete -c skilltap -n '__fish_seen_subcommand_from config; and __fish_seen_subcommand_from security' -l scan -xa 'semantic static none' -d 'Scan level'
complete -c skilltap -n '__fish_seen_subcommand_from config; and __fish_seen_subcommand_from security' -l on-warn -xa 'prompt fail install' -d 'Warning behavior'
complete -c skilltap -n '__fish_seen_subcommand_from config; and __fish_seen_subcommand_from security' -l trust-add -d 'Append a glob pattern to security.trust'
complete -c skilltap -n '__fish_seen_subcommand_from config; and __fish_seen_subcommand_from security' -l trust-remove -d 'Remove a glob pattern from security.trust'
complete -c skilltap -n '__fish_seen_subcommand_from config; and __fish_seen_subcommand_from security' -l trust-list -d 'Print current trust patterns'

# tap subcommands
complete -c skilltap -n '__fish_seen_subcommand_from tap; and not __fish_seen_subcommand_from add remove list info init' -a 'add' -d 'Add a tap'
complete -c skilltap -n '__fish_seen_subcommand_from tap; and not __fish_seen_subcommand_from add remove list info init' -a 'remove' -d 'Remove a tap'
complete -c skilltap -n '__fish_seen_subcommand_from tap; and not __fish_seen_subcommand_from add remove list info init' -a 'list' -d 'List taps'
complete -c skilltap -n '__fish_seen_subcommand_from tap; and not __fish_seen_subcommand_from add remove list info init' -a 'info' -d 'Show tap details'
complete -c skilltap -n '__fish_seen_subcommand_from tap; and not __fish_seen_subcommand_from add remove list info init' -a 'init' -d 'Scaffold a tap repo'
complete -c skilltap -n '__fish_seen_subcommand_from tap; and __fish_seen_subcommand_from add' -l type -xa 'git' -d 'Tap type'
complete -c skilltap -n '__fish_seen_subcommand_from tap; and __fish_seen_subcommand_from remove' -l yes -d 'Skip confirmation'
complete -c skilltap -n '__fish_seen_subcommand_from tap; and __fish_seen_subcommand_from remove' -xa '(skilltap --get-completions tap-names 2>/dev/null)'
complete -c skilltap -n '__fish_seen_subcommand_from tap; and __fish_seen_subcommand_from list' -l json -d 'JSON output'
complete -c skilltap -n '__fish_seen_subcommand_from tap; and __fish_seen_subcommand_from info' -xa '(skilltap --get-completions tap-names 2>/dev/null)'
complete -c skilltap -n '__fish_seen_subcommand_from tap; and __fish_seen_subcommand_from info' -l json -d 'JSON output'

# doctor flags
complete -c skilltap -n '__fish_seen_subcommand_from doctor' -l json -d 'JSON output'
complete -c skilltap -n '__fish_seen_subcommand_from doctor' -l fix -d 'Auto-fix issues'

# completions shells
complete -c skilltap -n '__fish_seen_subcommand_from completions' -xa 'bash zsh fish'

# status flags
complete -c skilltap -n '__fish_seen_subcommand_from status' -l json -d 'Output as JSON'

# config telemetry subcommands
complete -c skilltap -n '__fish_seen_subcommand_from config; and __fish_seen_subcommand_from telemetry; and not __fish_seen_subcommand_from status enable disable' -xa 'status enable disable'

# self-update flags
complete -c skilltap -n '__fish_seen_subcommand_from self-update' -l force -d 'Bypass cache and re-install even if already on latest'

# migrate flags
complete -c skilltap -n '__fish_seen_subcommand_from migrate' -l json -d 'Output as JSON'

# sync flags
complete -c skilltap -n '__fish_seen_subcommand_from sync' -l json -d 'Output the plan as JSON'
complete -c skilltap -n '__fish_seen_subcommand_from sync' -l apply -d 'Apply the plan'

# try flags
complete -c skilltap -n '__fish_seen_subcommand_from try' -l json -d 'Output as JSON'
complete -c skilltap -n '__fish_seen_subcommand_from try' -l skip-scan -d 'Skip the static security scan'

# toggle flags + dynamic plugin names
complete -c skilltap -n '__fish_seen_subcommand_from toggle' -l json -d 'Output as JSON'
complete -c skilltap -n '__fish_seen_subcommand_from toggle' -xa '(skilltap --get-completions installed-plugins 2>/dev/null)'

# adopt flags
complete -c skilltap -n '__fish_seen_subcommand_from adopt' -l scope -xa 'project global' -d 'Adopt into scope'
complete -c skilltap -n '__fish_seen_subcommand_from adopt' -l source -xa '${agentList}' -d 'Filter picker to one source'
complete -c skilltap -n '__fish_seen_subcommand_from adopt' -l also -xa '${agentList}' -d 'Symlink to agent dir'
complete -c skilltap -n '__fish_seen_subcommand_from adopt' -l move -d 'Physically move dir on adopt'
complete -c skilltap -n '__fish_seen_subcommand_from adopt' -l skip-scan -d 'Skip security scan'
complete -c skilltap -n '__fish_seen_subcommand_from adopt' -l yes -d 'Auto-accept'
complete -c skilltap -n '__fish_seen_subcommand_from adopt' -l json -d 'Output as JSON'

# move flags
complete -c skilltap -n '__fish_seen_subcommand_from move' -l scope -xa 'project global' -d 'Target scope'
complete -c skilltap -n '__fish_seen_subcommand_from move' -l also -xa '${agentList}' -d 'Symlink to agent dir'
complete -c skilltap -n '__fish_seen_subcommand_from move' -xa '(skilltap --get-completions installed-skills 2>/dev/null)'`;
}
