import { TEMPLATE_NAMES, VALID_AGENT_IDS } from "@skilltap/core";

export function generateFishCompletions(): string {
  const agentList = VALID_AGENT_IDS.join(" ");
  const templateList = TEMPLATE_NAMES.join(" ");
  return `# skilltap fish completions
# Generated by: skilltap completions fish

# Disable default file completions for skilltap
complete -c skilltap -f

# Top-level commands
complete -c skilltap -n '__fish_use_subcommand' -a status -d 'Show agent mode configuration'
complete -c skilltap -n '__fish_use_subcommand' -a install -d 'Install a skill'
complete -c skilltap -n '__fish_use_subcommand' -a remove -d 'Remove an installed skill'
complete -c skilltap -n '__fish_use_subcommand' -a list -d 'List installed skills'
complete -c skilltap -n '__fish_use_subcommand' -a update -d 'Update installed skills'
complete -c skilltap -n '__fish_use_subcommand' -a find -d 'Search for skills'
complete -c skilltap -n '__fish_use_subcommand' -a link -d 'Symlink a local skill'
complete -c skilltap -n '__fish_use_subcommand' -a unlink -d 'Remove a linked skill'
complete -c skilltap -n '__fish_use_subcommand' -a info -d 'Show skill details'
complete -c skilltap -n '__fish_use_subcommand' -a create -d 'Create a new skill'
complete -c skilltap -n '__fish_use_subcommand' -a verify -d 'Validate a skill'
complete -c skilltap -n '__fish_use_subcommand' -a config -d 'Interactive setup wizard'
complete -c skilltap -n '__fish_use_subcommand' -a tap -d 'Manage taps'
complete -c skilltap -n '__fish_use_subcommand' -a doctor -d 'Check environment and state'
complete -c skilltap -n '__fish_use_subcommand' -a completions -d 'Generate shell completions'
complete -c skilltap -n '__fish_use_subcommand' -a self-update -d 'Update the skilltap binary'

# install flags
complete -c skilltap -n '__fish_seen_subcommand_from install' -l project -d 'Install to project scope'
complete -c skilltap -n '__fish_seen_subcommand_from install' -l global -d 'Install to global scope'
complete -c skilltap -n '__fish_seen_subcommand_from install' -l also -xa '${agentList}' -d 'Symlink to agent dir'
complete -c skilltap -n '__fish_seen_subcommand_from install' -l ref -x -d 'Branch or tag'
complete -c skilltap -n '__fish_seen_subcommand_from install' -l yes -d 'Auto-accept'
complete -c skilltap -n '__fish_seen_subcommand_from install' -l strict -d 'Abort on warnings'
complete -c skilltap -n '__fish_seen_subcommand_from install' -l no-strict -d 'Override strict config'
complete -c skilltap -n '__fish_seen_subcommand_from install' -l semantic -d 'Force semantic scan'
complete -c skilltap -n '__fish_seen_subcommand_from install' -l skip-scan -d 'Skip security scan'
complete -c skilltap -n '__fish_seen_subcommand_from install' -l quiet -d 'Suppress install step details'
complete -c skilltap -n '__fish_seen_subcommand_from install' -xa '(skilltap --get-completions tap-skills 2>/dev/null)'

# remove flags
complete -c skilltap -n '__fish_seen_subcommand_from remove' -l project -d 'Remove from project scope'
complete -c skilltap -n '__fish_seen_subcommand_from remove' -l yes -d 'Skip confirmation'
complete -c skilltap -n '__fish_seen_subcommand_from remove' -xa '(skilltap --get-completions installed-skills 2>/dev/null)'

# list flags
complete -c skilltap -n '__fish_seen_subcommand_from list' -l global -d 'Global scope'
complete -c skilltap -n '__fish_seen_subcommand_from list' -l project -d 'Project scope'
complete -c skilltap -n '__fish_seen_subcommand_from list' -l json -d 'JSON output'

# update flags
complete -c skilltap -n '__fish_seen_subcommand_from update' -l yes -d 'Auto-accept'
complete -c skilltap -n '__fish_seen_subcommand_from update' -l strict -d 'Abort on warnings'
complete -c skilltap -n '__fish_seen_subcommand_from update' -l semantic -d 'Force semantic scan'
complete -c skilltap -n '__fish_seen_subcommand_from update' -l json -d 'Output result as JSON'
complete -c skilltap -n '__fish_seen_subcommand_from update' -s c -l check -d 'Check for updates without applying'
complete -c skilltap -n '__fish_seen_subcommand_from update' -xa '(skilltap --get-completions installed-skills 2>/dev/null)'

# find flags
complete -c skilltap -n '__fish_seen_subcommand_from find' -l json -d 'JSON output'
complete -c skilltap -n '__fish_seen_subcommand_from find' -s i -d 'Interactive mode'
complete -c skilltap -n '__fish_seen_subcommand_from find' -s l -l local -d 'Search local taps only'

# link flags
complete -c skilltap -n '__fish_seen_subcommand_from link' -l global -d 'Global scope'
complete -c skilltap -n '__fish_seen_subcommand_from link' -l project -d 'Project scope'
complete -c skilltap -n '__fish_seen_subcommand_from link' -l also -xa '${agentList}' -d 'Agent symlink'

# unlink flags
complete -c skilltap -n '__fish_seen_subcommand_from unlink' -l yes -d 'Skip confirmation'
complete -c skilltap -n '__fish_seen_subcommand_from unlink' -xa '(skilltap --get-completions linked-skills 2>/dev/null)'

# info — dynamic installed skill names
complete -c skilltap -n '__fish_seen_subcommand_from info' -xa '(skilltap --get-completions installed-skills 2>/dev/null)'

# create flags
complete -c skilltap -n '__fish_seen_subcommand_from create' -l template -xa '${templateList}' -d 'Template type'
complete -c skilltap -n '__fish_seen_subcommand_from create' -l dir -d 'Target directory'

# verify flags
complete -c skilltap -n '__fish_seen_subcommand_from verify' -l json -d 'JSON output'

# config subcommands
complete -c skilltap -n '__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from agent-mode telemetry get set edit' -a 'agent-mode' -d 'Configure agent mode'
complete -c skilltap -n '__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from agent-mode telemetry get set edit' -a 'telemetry' -d 'Manage telemetry settings'
complete -c skilltap -n '__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from agent-mode telemetry get set edit' -a 'get' -d 'Get a config value'
complete -c skilltap -n '__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from agent-mode telemetry get set edit' -a 'set' -d 'Set a config value'
complete -c skilltap -n '__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from agent-mode telemetry get set edit' -a 'edit' -d 'Open config in editor'
complete -c skilltap -n '__fish_seen_subcommand_from config; and __fish_seen_subcommand_from get' -l json -d 'Output as JSON'

# tap subcommands
complete -c skilltap -n '__fish_seen_subcommand_from tap; and not __fish_seen_subcommand_from add remove list update init install' -a 'add' -d 'Add a tap'
complete -c skilltap -n '__fish_seen_subcommand_from tap; and not __fish_seen_subcommand_from add remove list update init install' -a 'remove' -d 'Remove a tap'
complete -c skilltap -n '__fish_seen_subcommand_from tap; and not __fish_seen_subcommand_from add remove list update init install' -a 'list' -d 'List taps'
complete -c skilltap -n '__fish_seen_subcommand_from tap; and not __fish_seen_subcommand_from add remove list update init install' -a 'update' -d 'Update taps'
complete -c skilltap -n '__fish_seen_subcommand_from tap; and not __fish_seen_subcommand_from add remove list update init install' -a 'init' -d 'Scaffold a tap repo'
complete -c skilltap -n '__fish_seen_subcommand_from tap; and not __fish_seen_subcommand_from add remove list update init install' -a 'install' -d 'Install skills from taps'
complete -c skilltap -n '__fish_seen_subcommand_from tap; and __fish_seen_subcommand_from remove update' -xa '(skilltap --get-completions tap-names 2>/dev/null)'
complete -c skilltap -n '__fish_seen_subcommand_from tap; and __fish_seen_subcommand_from install' -l tap -xa '(skilltap --get-completions tap-names 2>/dev/null)' -d 'Scope to one tap'
complete -c skilltap -n '__fish_seen_subcommand_from tap; and __fish_seen_subcommand_from install' -l project -d 'Install to project scope'
complete -c skilltap -n '__fish_seen_subcommand_from tap; and __fish_seen_subcommand_from install' -l global -d 'Install to global scope'
complete -c skilltap -n '__fish_seen_subcommand_from tap; and __fish_seen_subcommand_from install' -l also -xa '${agentList}' -d 'Symlink to agent dir'
complete -c skilltap -n '__fish_seen_subcommand_from tap; and __fish_seen_subcommand_from install' -l yes -d 'Auto-select all and install'
complete -c skilltap -n '__fish_seen_subcommand_from tap; and __fish_seen_subcommand_from install' -l strict -d 'Abort on warnings'
complete -c skilltap -n '__fish_seen_subcommand_from tap; and __fish_seen_subcommand_from install' -l no-strict -d 'Override strict config'
complete -c skilltap -n '__fish_seen_subcommand_from tap; and __fish_seen_subcommand_from install' -l semantic -d 'Force semantic scan'
complete -c skilltap -n '__fish_seen_subcommand_from tap; and __fish_seen_subcommand_from install' -l skip-scan -d 'Skip security scan'

# doctor flags
complete -c skilltap -n '__fish_seen_subcommand_from doctor' -l json -d 'JSON output'
complete -c skilltap -n '__fish_seen_subcommand_from doctor' -l fix -d 'Auto-fix issues'

# completions shells
complete -c skilltap -n '__fish_seen_subcommand_from completions' -xa 'bash zsh fish'

# status flags
complete -c skilltap -n '__fish_seen_subcommand_from status' -l json -d 'Output as JSON'

# config telemetry subcommands
complete -c skilltap -n '__fish_seen_subcommand_from config; and __fish_seen_subcommand_from telemetry; and not __fish_seen_subcommand_from status enable disable' -xa 'status enable disable'

# self-update flags
complete -c skilltap -n '__fish_seen_subcommand_from self-update' -l force -d 'Bypass cache and re-install even if already on latest'`;
}
