pub mod adoption;
pub mod bootstrap;
pub mod compatibility;
pub mod daemon;
pub mod domain;
pub mod executor;
pub mod foreground_update;
pub mod hook_mapping;
pub mod instructions;
pub mod lifecycle_operation;
pub mod managed_projection;
pub mod marketplace;
pub mod materialization;
pub mod native_config;
pub mod operation_graph;
pub mod plugin_graph;
pub mod publication;
pub mod reconciliation;
pub mod runtime;
pub mod skill;
pub mod skill_compatibility;
pub mod skill_lifecycle;
pub mod skill_source;
pub mod storage;
pub mod updates;

pub const VERSION: &str = env!("CARGO_PKG_VERSION");
