export type { SourceAdapter } from "./types"
export { gitAdapter } from "./git"
export { githubAdapter } from "./github"
export { localAdapter } from "./local"
export { resolveSource } from "./resolve"
